// Copyright 2023 The Cockroach Authors.
//
// Licensed as a CockroachDB Enterprise file under the Cockroach Community
// License (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt

// Code generated by pkg/ccl/backupccl/testgen, DO NOT EDIT.

package backupccl

import (
	"testing"

	"github.com/cockroachdb/cockroach/pkg/util/leaktest"
)

func TestRestoreEntryCover_numBackups_1(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 1)
}

func TestRestoreEntryCover_numBackups_2(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 2)
}

func TestRestoreEntryCover_numBackups_3(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 3)
}

func TestRestoreEntryCover_numBackups_5(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 5)
}

func TestRestoreEntryCover_numBackups_9(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 9)
}

func TestRestoreEntryCover_numBackups_10(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 10)
}

func TestRestoreEntryCover_numBackups_11(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 11)
}

func TestRestoreEntryCover_numBackups_12(t *testing.T) {
	defer leaktest.AfterTest(t)()

	runTestRestoreEntryCover(t, 12)
}
